name: 🚀 Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['feature', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand and prioritize your request.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: 'Describe the feature from a user''s perspective: "As a [type of user], I want [goal] so that [benefit]."'
      placeholder: 'As a user, I want to...'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Provide a list of criteria that must be met for this feature to be considered complete.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternative approaches might be...
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Which package would this feature affect?
      multiple: true
      options:
        - '@discuno/web (main app)'
        - '@discuno/atoms (component library)'
        - 'Monorepo configuration'
        - 'Documentation'
        - 'Other'
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please review the following checklist before submitting.
      options:
        - label: I have searched existing issues to ensure this is not a duplicate.
          required: true
        - label: I have provided a clear and descriptive title.
          required: true
        - label: I have provided clear acceptance criteria.
          required: true
        - label: I have considered the impact on existing functionality.
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true