name: 🚀 Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['feature', 'enhancement']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternative approaches might be...
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Which area would this feature affect?
      multiple: true
      options:
        - 'Web Application (apps/web)'
        - 'Monorepo configuration'
        - 'Documentation'
        - 'Other'
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - 'Low - Nice to have'
        - 'Medium - Would be helpful'
        - 'High - Important for my use case'
        - 'Critical - Blocking my project'
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I'd be willing to submit a PR for this feature
        - label: I'd be willing to help test this feature
        - label: I'd be willing to help with documentation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
