name: Code Scanning

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run code scanning daily at 3 AM UTC
    - cron: '0 3 * * *'

env:
  FORCE_COLOR: 1
  CI: true

# Ensure proper permissions for Copilot Autofix
permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  codeql:
    name: CodeQL Analysis with Autofix
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      pull-requests: write # Required for Copilot Autofix

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          # Fetch full history for better analysis
          fetch-depth: 0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: +security-and-quality
          config-file: ./.github/codeql-config.yml

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Build packages
        env:
          SKIP_ENV_VALIDATION: true
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          # Stripe keys (use placeholder if not set)
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY || 'sk_test_placeholder' }}
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY || 'pk_test_placeholder' }}
          # Cal.com API credentials
          NEXT_PUBLIC_X_CAL_ID: ${{ secrets.CALCOM_CLIENT_ID || 'placeholder' }}
          X_CAL_SECRET_KEY: ${{ secrets.CALCOM_CLIENT_SECRET || 'placeholder' }}
          # Email service (Resend)
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY || 're_placeholder' }}
          # Email provider for NextAuth (Nodemailer)
          AUTH_EMAIL_SERVER: ${{ secrets.AUTH_EMAIL_SERVER || 'smtp://placeholder@example.com:password@smtp.placeholder.com:587' }}
          AUTH_EMAIL_FROM: ${{ secrets.AUTH_EMAIL_FROM || 'noreply@placeholder.com' }}
          # Other API keys that might be needed during build
          NEXTAUTH_SECRET: 'test-secret-for-build-only'
          NEXTAUTH_URL: 'http://localhost:3000'
        run: pnpm build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:${{matrix.language}}'
          # Upload results to enable Copilot Autofix
          upload: true

  trivy-scan:
    name: Trivy Scan with Autofix
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      security-events: write
      pull-requests: write # Required for Copilot Autofix

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          trivy-config: 'trivy.yaml'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy'
